config/routes.rb
Rails.application.routes.draw do
  get 'components/header'
  get 'components/cities_bloc'
  get 'components/explore_museum_bloc'
  get 'components/event_bloc'
  get 'components/could_be_interested_bloc'
  get 'components/filter'
  get 'components/museum_cards'
  get 'components/event_cards'
  get 'components/weather_bloc'
  get 'components/how_to_get_there_block'
  get 'components/unmissable_block'
  get 'components/map_block'
  get 'components/current_events_blocks'
  get 'components/coming_events_block'
  get 'components/add_establishment_block'
  get 'components/footer'
  get 'pages/index'
  get 'pages/home_knownuser_pref_geo'
  get 'pages/home_knownuser_pref_nogeo'
  get 'pages/home_knownuser_nopref_geo'
  get 'pages/home_knownuser_nopref_nogeo'
  get 'pages/home_unknownuser_geo'
  get 'pages/home_unkownuser_nogeo'
  get 'pages/museum'
  get 'pages/event'
  get 'pages/add_museum'
  get 'pages/add_event'
  get 'pages/user_profile'
  get 'pages/museum_profile'
  get 'pages/buy_tickets'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  def header
  end

  def cities_bloc
  end

  def explore_museum_bloc
  end

  def event_bloc
  end

  def could_be_interested_bloc
  end

  def filter
  end

  def museum_cards
  end

  def event_cards
  end

  def weather_bloc
  end

  def how_to_get_there_block
  end

  def unmissable_block
  end

  def map_block
  end

  def current_events_blocks
  end

  def coming_events_block
  end

  def add_establishment_block
  end

  def footer
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def home_knownuser_pref_geo
  end

  def home_knownuser_pref_nogeo
  end

  def home_knownuser_nopref_geo
  end

  def home_knownuser_nopref_nogeo
  end

  def home_unknownuser_geo
  end

  def home_unkownuser_nogeo
  end

  def museum
  end

  def event
  end

  def add_museum
  end

  def add_event
  end

  def user_profile
  end

  def museum_profile
  end

  def buy_tickets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartysandbox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/add_event.html.erb
<h1>Pages#add_event</h1>
<p>Find me in app/views/pages/add_event.html.erb</p>

app/views/pages/add_museum.html.erb
<h1>Pages#add_museum</h1>
<p>Find me in app/views/pages/add_museum.html.erb</p>

app/views/pages/buy_tickets.html.erb
<h1>Pages#buy_tickets</h1>
<p>Find me in app/views/pages/buy_tickets.html.erb</p>

app/views/pages/event.html.erb
<h1>Pages#event</h1>
<p>Find me in app/views/pages/event.html.erb</p>

app/views/pages/home_knownuser_nopref_geo.html.erb
<h1>Pages#home_knownuser_nopref_geo</h1>
<p>Find me in app/views/pages/home_knownuser_nopref_geo.html.erb</p>

app/views/pages/home_knownuser_nopref_nogeo.html.erb
<h1>Pages#home_knownuser_nopref_nogeo</h1>
<p>Find me in app/views/pages/home_knownuser_nopref_nogeo.html.erb</p>

app/views/pages/home_knownuser_pref_geo.html.erb
<h1>Pages#home_knownuser_pref_geo</h1>
<p>Find me in app/views/pages/home_knownuser_pref_geo.html.erb</p>

app/views/pages/home_knownuser_pref_nogeo.html.erb
<h1>Pages#home_knownuser_pref_nogeo</h1>
<p>Find me in app/views/pages/home_knownuser_pref_nogeo.html.erb</p>

app/views/pages/home_unknownuser_geo.html.erb
<h1>Pages#home_unknownuser_geo</h1>
<p>Find me in app/views/pages/home_unknownuser_geo.html.erb</p>

app/views/pages/home_unkownuser_nogeo.html.erb
<h1>Pages#home_unkownuser_nogeo</h1>
<p>Find me in app/views/pages/home_unkownuser_nogeo.html.erb</p>

app/views/pages/index.html.erb
<div class="container">
<h1>Pages#index</h1>
<h2>Pages</h2>
<li><%= link_to "pages_home_knownuser_pref_geo", pages_home_knownuser_pref_geo_path %></li>
<li><%= link_to "pages_home_knownuser_pref_nogeo", pages_home_knownuser_pref_nogeo_path %></li>
<li><%= link_to "pages_home_knownuser_nopref_geo", pages_home_knownuser_nopref_geo_path %></li>
<li><%= link_to "pages_home_knownuser_nopref_nogeo", pages_home_knownuser_nopref_nogeo_path %></li>
<li><%= link_to "pages_home_unknownuser_geo", pages_home_unknownuser_geo_path %></li>
<li><%= link_to "pages_home_unknownuser_nogeo", pages_home_unkownuser_nogeo_path %></li>
<li><%= link_to "pages_museum", pages_museum_path %></li>
<li><%= link_to "pages_event", pages_event_path %></li>
<li><%= link_to "pages_add_museum", pages_add_museum_path %></li>
<li><%= link_to "pages_add_event", pages_add_event_path %></li>
<li><%= link_to "pages_user_profile", pages_user_profile_path %></li>
<li><%= link_to "pages_museum_profile", pages_museum_profile_path %></li>
<li><%= link_to "pages_buy_tickets", pages_buy_tickets_path %></li>
<h2>Components</h2>
<li><%= link_to "components_header", components_header_path %></li>
<li><%= link_to "components_cities_bloc", components_cities_bloc_path %></li>
<li><%= link_to "components_explore_museum_bloc", components_explore_museum_bloc_path %></li>
<li><%= link_to "components_event_bloc", components_event_bloc_path %></li>
<li><%= link_to "components_could_be_interested_bloc", components_could_be_interested_bloc_path %></li>
<li><%= link_to "components_filter", components_filter_path %></li>
<li><%= link_to "components_museum_cards", components_museum_cards_path %></li>
<li><%= link_to "components_event_cards", components_event_cards_path %></li>
<li><%= link_to "components_weather_bloc", components_weather_bloc_path %></li>
<li><%= link_to "components_how_to_get_there_block", components_how_to_get_there_block_path %></li>
<li><%= link_to "components_unmissable_block", components_unmissable_block_path %></li>
<li><%= link_to "components_map_block", components_map_block_path %></li>
<li><%= link_to "components_current_events_blocks", components_current_events_blocks_path %></li>
<li><%= link_to "components_coming_events_blocks", components_coming_events_blocks_path %></li>
<li><%= link_to "components_add_establishment_block", components_add_establishment_block_path %></li>
<li><%= link_to "components_footer", components_footer_path %></li>
</div>

app/views/pages/museum.html.erb
<h1>Pages#museum</h1>
<p>Find me in app/views/pages/museum.html.erb</p>

app/views/pages/museum_profile.html.erb
<h1>Pages#museum_profile</h1>
<p>Find me in app/views/pages/museum_profile.html.erb</p>

app/views/pages/user_profile.html.erb
<h1>Pages#user_profile</h1>
<p>Find me in app/views/pages/user_profile.html.erb</p>